/// <reference types="vite-plugin-pwa/react" />
/**
 * The one place the service worker is registered, and the only wire between it
 * and the interface.
 *
 * `virtual:pwa-register/react` is generated by `vite-plugin-pwa`. It is
 * imported here and nowhere else, so the rest of the app — and every unit test
 * — stays free of a build-time virtual module. Vitest aliases it to a stub
 * (`src/test/pwa-register-stub.ts`), which is why `UpdatePrompt` takes plain
 * props: the decision is testable without a service worker at all.
 *
 * `updateServiceWorker(true)` is called from exactly one place: the button in
 * `UpdatePrompt`. Nothing here calls it on a timer, on a route change, or on
 * registration (practices F4).
 */
import { useRegisterSW } from 'virtual:pwa-register/react';
import { useExamStore } from '~/store/exam';
import { UpdatePrompt } from './UpdatePrompt';

export function ServiceWorkerUpdate() {
  const {
    needRefresh: [needRefresh],
    updateServiceWorker,
  } = useRegisterSW();

  // An attempt on the device — paused, or simply not yet scored. Accepting an
  // update reloads, and the attempt would survive that (it is persisted), but
  // the offer is withheld anyway: a learner sitting an exam is not the audience
  // for a software update.
  const examInProgress = useExamStore((state) => state.record.active !== null);

  return (
    <UpdatePrompt
      waiting={needRefresh}
      examInProgress={examInProgress}
      onUpdate={() => {
        void updateServiceWorker(true);
      }}
    />
  );
}
