/**
 * Regenerates `src/content/rules.json` from `docs/research/manual-spine.md` §2.
 *
 * This is an authoring tool, not part of the app or the validator. It exists so
 * that no rule quote is ever retyped by hand: every quote in the question bank
 * is carried straight from the research spine, and every fragment is checked
 * against `docs/research/tn-dl-manual-extract.txt` before it is written out.
 *
 * The spine's quote cells sometimes hold more than one verbatim fragment:
 *   - two separate quotes joined by " / " (two different sentences/pages)
 *   - one quote with an elision marked by "..."
 *   - a trailing `[extraction unclear - ...]` editorial note
 * Only contiguous fragments that survive normalization-matching against the
 * extract are kept, longest first.
 *
 *   node scripts/extract-rules.mjs           # write src/content/rules.json
 *   node scripts/extract-rules.mjs --report  # print rules with no usable quote
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { normalizeForMatch } from './lib/content-normalize.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const spine = readFileSync(join(root, 'docs/research/manual-spine.md'), 'utf8');
const extract = readFileSync(join(root, 'docs/research/tn-dl-manual-extract.txt'), 'utf8');
const haystack = normalizeForMatch(extract);

const SECTION_2 = spine.slice(spine.indexOf('# 2. Testable-rule inventory'), spine.indexOf('# 3. Road sign inventory'));

/** @type {{id:string,group:string,topic:string,rule:string,pdfPage:number,printedPage:number|null,quote:string,extraQuotes:string[]}[]} */
const rules = [];
const rejected = [];

let group = '';
for (const line of SECTION_2.split(/\r?\n/)) {
  const heading = /^##\s+(2\.\d+)\s+(.*)$/.exec(line);
  if (heading) {
    group = heading[2].trim();
    continue;
  }
  if (!/^\|\s*R\d{3}\s*\|/.test(line)) continue;

  const cells = line.split('|').slice(1, -1).map((c) => c.trim());
  const [id, topic, rule, quoteCell, pageCell] = cells;

  const pdfPage = Number(/(\d+)/.exec(pageCell)?.[1]);
  const printedPage = pdfPage >= 15 && pdfPage <= 132 ? pdfPage - 14 : null;

  const fragments = [];
  for (const candidate of quoteFragments(quoteCell)) {
    for (const variant of quoteVariants(candidate)) {
      if (haystack.includes(normalizeForMatch(variant))) {
        fragments.push(variant);
        break;
      }
    }
  }
  fragments.sort((a, b) => b.length - a.length);

  if (fragments.length === 0) {
    rejected.push({ id, quoteCell });
    continue;
  }

  rules.push({
    id,
    group,
    topic,
    rule,
    pdfPage,
    printedPage,
    quote: fragments[0],
    extraQuotes: fragments.slice(1),
  });
}

/**
 * Pull every candidate contiguous verbatim fragment out of a spine quote cell.
 * @param {string} cell
 */
function quoteFragments(cell) {
  const withoutNotes = cell.replace(/`\[[^`]*\]`/g, ' ');
  const quoted = [...withoutNotes.matchAll(/[“"]([^“”"]+)[”"]/g)].map((m) => m[1]);
  const out = [];
  for (const q of quoted) {
    const pieces = [q, ...q.split(/\s*(?:\.\.\.|…)\s*/), ...q.split(/\s+\/\s+/)];
    for (const piece of pieces) {
      const trimmed = piece.trim().replace(/^[•\s]+/, '').replace(/\s*\/\s*$/, '').trim();
      if (trimmed.length >= 25 && !out.includes(trimmed)) out.push(trimmed);
    }
  }
  return out;
}

/**
 * The spine renders the manual's inner curly double quotes as single quotes
 * (e.g. `'GDL'` where the PDF has `“GDL”`). Try both readings; only a variant
 * that actually occurs in the extract is ever kept.
 * @param {string} fragment
 */
function quoteVariants(fragment) {
  const variants = [fragment];
  if (/'[^']+'/.test(fragment)) variants.push(fragment.replace(/'([^']+)'/g, '"$1"'));
  return variants;
}

if (process.argv.includes('--report')) {
  console.log(`rules with a verified quote: ${rules.length}`);
  console.log(`rules with no verbatim-matching fragment: ${rejected.length}`);
  for (const r of rejected) console.log(`  ${r.id}  ${r.quoteCell.slice(0, 110)}`);
} else {
  const payload = {
    source: 'docs/research/manual-spine.md §2 (Testable-rule inventory)',
    note: 'Generated by scripts/extract-rules.mjs. Every quote below was verified to appear verbatim (after whitespace/quote/dash normalization) in docs/research/tn-dl-manual-extract.txt.',
    generatedFrom: { rulesInSpine: rules.length + rejected.length, rulesWithVerifiedQuote: rules.length },
    rules,
  };
  writeFileSync(join(root, 'src/content/rules.json'), `${JSON.stringify(payload, null, 2)}\n`);
  console.log(`wrote src/content/rules.json — ${rules.length} rules with verified quotes (${rejected.length} dropped)`);
}
